services:
    idci_merge_token.mergeable_object.handler.twig:
        class: IDCI\Bundle\MergeTokenBundle\Mergeable\TwigMergeableObjectHandler
        arguments: ["@twig", "@service_container", "%idci_merge_token.mergeable_objects%"]

    ## Events Subscriber ##
    tms_merge_token.event.subscriber.serializer:
        class: IDCI\Bundle\MergeTokenBundle\Event\Subscriber\SerializerSubscriber
        arguments: ["@idci_merge_token.mergeable_object.handler.twig"]
        tags:
            - { name: jms_serializer.event_subscriber }

    ## Twig Extensions ##

    idci_merge_token.twig.merge_token_extension:
        class: IDCI\Bundle\MergeTokenBundle\Twig\MergeTokenExtension
        arguments: ["@idci_merge_token.mergeable_object.handler.twig"]
        tags:
            - { name: twig.extension }
